### ISSUE TITLE
Compilation errors with latest Quicklisp

### ISSUE THREAD

**Issue by ebzzry** [vseloved/cl-nlp#34]
After updating my Quicklisp installation with:

    (ql:update-dist "quicklisp")

I can longer load cl-nlp with

     (ql:quickload "cl-nlp")

**Comment by ebzzry** [comment]
In the meantime, I backtracked my QL installation with:

```
(use-package :ql-dist)
(available-versions (dist "quicklisp"))
(install-dist "http://beta.quicklisp.org/dist/quicklisp/2019-07-11/distinfo.txt")
```

**Comment by vseloved** [comment]
Can you provide an error log? What exactly fails? And which implementation are you using?
If you don't see any errors you can either try to perform `(ql:quickload "cl-nlp" :verbose t)` or `(asdf:load-system :cl-nlp)`

**Comment by ebzzry** [comment]
Unfortunately, I no longer have the error log. 

I reinstalled the QL environment, and recloned cl-nlp, and it works now. I’m closing this issue now.
